version: '3.6'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

#  backend-test:
#    build:
#      target: backend-test-stage
#    volumes:
#      - ./artifacts/reports:/reports
#    links:
#      - db

  backend:
    image: "jrr/aplazame_backend"
    build:
      dockerfile: Dockerfile
      context: .
      target: backend-production-stage
    ports:
      - "5000:5000"
    links:
      - db